image: golang:1.23.2

stages:
  - build checks

build:
  stage: build checks
  artifacts:
    paths:
      - ./bin/witness
  script:
    - make clean build

test:
  stage: build checks
  script:
    - make test

vet:
  stage: build checks
  script:
    - make vet
