[build]
  base = "docs-website/"
  command = "npm run build"
  publish = "build/"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../docs/"

[build.environment]
  NODE_VERSION = "18.12.1"
