// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      label: 'About',
      id: 'docs/README',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Attestor Types',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/attestors',
        },
      ],
    },
    {
      type: 'doc',
      label: 'New Contributor Guide',
      id: 'CONTRIBUTING',
    },
    {
      type: 'doc',
      label: 'Code of Conduct',
      id: 'CODE_OF_CONDUCT',
    },
  ],
}

module.exports = sidebars
