permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
name: test-github-token
on: [push, pull_request]
jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build

      - name: Test
        run: ./bin/witness run -l debug -s test -a github --enable-archivist -o test.json --signer-fulcio-url https://fulcio.sigstore.dev --signer-fulcio-oidc-issuer https://oauth2.sigstore.dev/auth --signer-fulcio-oidc-client-id sigstore --timestamp-servers https://freetsa.org/tsr -- echo "hello" > test.txt
      - name: log output
        run: cat test.json
