name: Verify License
on:
  workflow_dispatch:
  push:
    branches: ["main", "release-*"]
  pull_request:
permissions:
  contents: read

jobs:
  license-check:
    name: license boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: Install addlicense
        run: go install github.com/google/addlicense@v1.1.1
      - name: Check license headers
        run: |
          set -e
          addlicense --check -l apache -c 'The Witness Contributors' --ignore "docs-website/**" --ignore "docs/**" -v *
